#!/usr/bin/env node
/**
 * Expand all loops in lessons.json to have exactly 5 links each.
 * Generates educationally appropriate content with 5 quiz questions per link.
 */

const fs = require('fs');
const path = require('path');

const FILE = path.join(__dirname, '..', 'src', 'data', 'lessons.json');
const data = JSON.parse(fs.readFileSync(FILE, 'utf8'));

// ─── Content templates per loop ───────────────────────────────────────────
// Each entry: [id_suffix, title, lesson_content]
// We only add what's missing (if loop has 2 links, we add links 3,4,5)

const EXTRA_LINKS = {
  // ══════════ MATH GRADE 1 ══════════
  counting_fun: [
    { id: 'counting_backwards', title: 'Counting Backwards', lesson: { sections: [{ heading: 'Count Down!', content: 'Counting backwards means going from a bigger number to a smaller one. Start at 10 and go down: 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, blast off!', visual: '🚀 10, 9, 8, 7, 6, 5, 4, 3, 2, 1... Blast off!' }, { heading: 'Why Count Backwards?', content: 'Counting backwards helps with subtraction! If you have 5 apples and eat 2, you count back: 5, 4, 3. You have 3 left!', visual: '🍎🍎🍎🍎🍎 → eat 2 → 🍎🍎🍎 = 3 left!' }], keyPoints: ['Counting backwards goes from big to small', 'It helps with subtraction', 'You can count back from any number'], funFact: 'Fun Fact: NASA counts backwards before launching rockets — they call it a countdown!' }, quiz: [{ q: 'What comes after 7 when counting backwards?', a: ['8', '6', '5', 'None of the above'], correct: 1, type: 'mcq' }, { q: 'Counting backwards means going from small to big.', a: ['True', 'False'], correct: 1, type: 'tf' }, { q: 'Count back: 10, 9, 8, __?', a: ['7', '6', '11', 'None of the above'], correct: 0, type: 'mcq' }, { q: 'Counting backwards helps with subtraction.', a: ['True', 'False'], correct: 0, type: 'tf' }, { q: 'What is 5 count back 2?', a: ['7', '3', '2', 'None of the above'], correct: 1, type: 'mcq' }] },
    { id: 'skip_counting', title: 'Skip Counting', lesson: { sections: [{ heading: 'Count by Twos!', content: 'Skip counting means jumping over numbers! When you count by 2s: 2, 4, 6, 8, 10. You skip every other number.', visual: '👟 Skip! 2, 4, 6, 8, 10 — like hopping over every other stone!' }, { heading: 'Count by Fives and Tens', content: 'You can also skip count by 5s: 5, 10, 15, 20. Or by 10s: 10, 20, 30, 40. This makes counting big groups faster!', visual: '✋ By 5s: 5, 10, 15, 20, 25 | 🔟 By 10s: 10, 20, 30, 40, 50' }], keyPoints: ['Skip counting skips over numbers', 'Count by 2s: 2, 4, 6, 8, 10', 'Count by 5s and 10s for big groups'], funFact: 'Fun Fact: Skip counting by 5s is how you count nickels! Each nickel is worth 5 cents.' }, quiz: [{ q: 'Skip count by 2s: 2, 4, 6, __?', a: ['7', '8', '9', 'None of the above'], correct: 1, type: 'mcq' }, { q: 'Skip counting means counting every number.', a: ['True', 'False'], correct: 1, type: 'tf' }, { q: 'Count by 5s: 5, 10, 15, __?', a: ['16', '20', '25', 'None of the above'], correct: 1, type: 'mcq' }, { q: 'Count by 10s: 10, 20, __?', a: ['25', '30', '21', 'None of the above'], correct: 1, type: 'mcq' }, { q: 'Skip counting helps you count faster.', a: ['True', 'False'], correct: 0, type: 'tf' }] },
    { id: 'number_order', title: 'Number Order', lesson: { sections: [{ heading: 'Smallest to Biggest', content: 'Putting numbers in order means arranging them from smallest to biggest (or biggest to smallest). 3, 1, 5, 2 in order is: 1, 2, 3, 5.', visual: '📊 Messy: 3, 1, 5, 2 → Ordered: 1, 2, 3, 5' }, { heading: 'Comparing Numbers', content: 'You can compare two numbers: 7 is greater than 3. We write 7 > 3. The hungry alligator eats the bigger number!', visual: '🐊 7 > 3 — The alligator opens its mouth toward the bigger number!' }], keyPoints: ['Order numbers from smallest to biggest', 'The > sign means "greater than"', 'The < sign means "less than"'], funFact: 'Fun Fact: The greater-than sign > looks like an alligator mouth — it always eats the bigger number!' }, quiz: [{ q: 'Which is the smallest: 8, 3, 6?', a: ['8', '3', '6', 'None of the above'], correct: 1, type: 'mcq' }, { q: '5 is greater than 9.', a: ['True', 'False'], correct: 1, type: 'tf' }, { q: 'Put in order: 4, 1, 7. What comes first?', a: ['4', '1', '7', 'None of the above'], correct: 1, type: 'mcq' }, { q: 'The > sign means "greater than."', a: ['True', 'False'], correct: 0, type: 'tf' }, { q: 'Which is bigger: 12 or 9?', a: ['9', '12', 'They are equal', 'None of the above'], correct: 1, type: 'mcq' }] },
  ],
  shape_hunt: [
    { id: 'shape_sides', title: 'Counting Sides & Corners', lesson: { sections: [{ heading: 'Sides and Corners', content: 'Every shape has sides (the straight lines) and corners (where sides meet). A triangle has 3 sides and 3 corners. A square has 4 sides and 4 corners.', visual: '🔺 Triangle: 3 sides, 3 corners | ⬛ Square: 4 sides, 4 corners' }, { heading: 'More Sides = New Shapes', content: 'A pentagon has 5 sides. A hexagon has 6 sides. The more sides a shape has, the more it starts to look like a circle!', visual: '⬠ Pentagon: 5 sides | ⬡ Hexagon: 6 sides' }], keyPoints: ['Sides are the straight lines of a shape', 'Corners are where two sides meet', 'A triangle has 3 sides, a square has 4'], funFact: 'Fun Fact: A stop sign is an octagon — it has 8 sides!' }, quiz: [{ q: 'How many sides does a triangle have?', a: ['2', '3', '4', 'None of the above'], correct: 1, type: 'mcq' }, { q: 'A square has 4 corners.', a: ['True', 'False'], correct: 0, type: 'tf' }, { q: 'How many sides does a hexagon have?', a: ['5', '6', '7', 'None of the above'], correct: 1, type: 'mcq' }, { q: 'Corners are where sides meet.', a: ['True', 'False'], correct: 0, type: 'tf' }, { q: 'A stop sign has ___ sides.', a: ['6', '8', '10', 'None of the above'], correct: 1, type: 'mcq' }] },
    { id: 'shape_3d', title: '3D Shapes Around Us', lesson: { sections: [{ heading: 'Flat vs Solid', content: '2D shapes are flat like paper — circles, squares, triangles. 3D shapes are solid like toys — spheres (balls), cubes (dice), cylinders (cans).', visual: '⚽ Sphere (ball) | 🎲 Cube (dice) | 🥫 Cylinder (can)' }, { heading: 'Shapes Everywhere!', content: 'Look around you! An ice cream cone is a cone shape. A basketball is a sphere. A cereal box is a rectangular prism!', visual: '🍦 Cone | 🏀 Sphere | 📦 Rectangular prism' }], keyPoints: ['2D shapes are flat, 3D shapes are solid', 'A ball is a sphere', 'A box is a rectangular prism'], funFact: 'Fun Fact: The pyramids in Egypt are actually 3D shapes — they\'re square pyramids with 4 triangle faces!' }, quiz: [{ q: 'What 3D shape is a ball?', a: ['Cube', 'Sphere', 'Cylinder', 'None of the above'], correct: 1, type: 'mcq' }, { q: 'A cube is a flat 2D shape.', a: ['True', 'False'], correct: 1, type: 'tf' }, { q: 'What shape is a soup can?', a: ['Sphere', 'Cone', 'Cylinder', 'None of the above'], correct: 2, type: 'mcq' }, { q: '3D shapes are solid.', a: ['True', 'False'], correct: 0, type: 'tf' }, { q: 'An ice cream cone is what shape?', a: ['Cone', 'Sphere', 'Cube', 'None of the above'], correct: 0, type: 'mcq' }] },
    { id: 'shape_symmetry', title: 'Symmetry & Patterns', lesson: { sections: [{ heading: 'Mirror Match!', content: 'Symmetry means both halves match! If you fold a butterfly in half, both wings look the same. A heart has symmetry too.', visual: '🦋 Fold in half → both sides match! That\'s symmetry!' }, { heading: 'Shape Patterns', content: 'Patterns repeat over and over. Circle, square, circle, square... what comes next? Circle! You can make patterns with any shapes.', visual: '🔴🟦🔴🟦🔴__? → 🟦!' }], keyPoints: ['Symmetry means both halves match', 'Butterflies and hearts have symmetry', 'Patterns repeat in order'], funFact: 'Fun Fact: Snowflakes have 6-way symmetry — every snowflake has 6 matching arms!' }, quiz: [{ q: 'What is symmetry?', a: ['When shapes are big', 'When both halves match', 'When shapes are colorful', 'None of the above'], correct: 1, type: 'mcq' }, { q: 'A butterfly has symmetry.', a: ['True', 'False'], correct: 0, type: 'tf' }, { q: 'Circle, square, circle, square, __?', a: ['Triangle', 'Circle', 'Square', 'None of the above'], correct: 1, type: 'mcq' }, { q: 'Snowflakes have 6-way symmetry.', a: ['True', 'False'], correct: 0, type: 'tf' }, { q: 'Which has symmetry?', a: ['The letter F', 'A heart shape', 'The number 7', 'None of the above'], correct: 1, type: 'mcq' }] },
  ],
  number_patterns: [
    { id: 'odd_even', title: 'Odd & Even Numbers', lesson: { sections: [{ heading: 'Even Numbers', content: 'Even numbers can be split into two equal groups. 2, 4, 6, 8, 10 are even. If you have 6 cookies, you can share them equally between 2 friends — 3 each!', visual: '🍪🍪🍪 | 🍪🍪🍪 = 6 cookies split evenly!' }, { heading: 'Odd Numbers', content: 'Odd numbers always have one left over when you try to split them. 1, 3, 5, 7, 9 are odd. If you have 5 apples and share with a friend, there\'s 1 left!', visual: '🍏🍏 | 🍏🍏 | 🍏 = 5 can\'t split evenly — 1 extra!' }], keyPoints: ['Even numbers: 2, 4, 6, 8, 10...', 'Odd numbers: 1, 3, 5, 7, 9...', 'Even numbers split into equal groups'], funFact: 'Fun Fact: Zero is an even number! You can split 0 into two equal groups of 0.' }, quiz: [{ q: 'Is 4 even or odd?', a: ['Even', 'Odd', 'Neither', 'None of the above'], correct: 0, type: 'mcq' }, { q: '7 is an even number.', a: ['True', 'False'], correct: 1, type: 'tf' }, { q: 'Which is odd: 6, 8, or 9?', a: ['6', '8', '9', 'None of the above'], correct: 2, type: 'mcq' }, { q: 'Even numbers can be split into two equal groups.', a: ['True', 'False'], correct: 0, type: 'tf' }, { q: 'What is the next even number after 10?', a: ['11', '12', '13', 'None of the above'], correct: 1, type: 'mcq' }] },
    { id: 'growing_patterns', title: 'Growing Patterns', lesson: { sections: [{ heading: 'Patterns That Grow', content: 'Some patterns get bigger each time! Like: 1, 3, 5, 7... each time we add 2. Or: 2, 4, 8... each time we double!', visual: '📈 Add 2: 1, 3, 5, 7, 9 (keeps growing by 2!)' }, { heading: 'Find the Rule', content: 'To find what comes next, look at how the numbers change. If they go up by 3 each time (1, 4, 7, 10...) the rule is "add 3."', visual: '🔍 1, 4, 7, 10, __ → Rule: +3 → Answer: 13!' }], keyPoints: ['Growing patterns get bigger each step', 'Find the rule: how much does it grow?', 'Add the same amount each time'], funFact: 'Fun Fact: The pattern 1, 1, 2, 3, 5, 8, 13... is called the Fibonacci sequence — each number is the sum of the two before it!' }, quiz: [{ q: 'What comes next: 2, 4, 6, __?', a: ['7', '8', '9', 'None of the above'], correct: 1, type: 'mcq' }, { q: 'Growing patterns always get bigger.', a: ['True', 'False'], correct: 0, type: 'tf' }, { q: 'Rule is +3. What comes after 7?', a: ['8', '9', '10', 'None of the above'], correct: 2, type: 'mcq' }, { q: '1, 3, 5, 7 — the rule is add 2.', a: ['True', 'False'], correct: 0, type: 'tf' }, { q: 'What comes next: 5, 10, 15, __?', a: ['16', '20', '25', 'None of the above'], correct: 1, type: 'mcq' }] },
  ],
  addition_intro: [
    { id: 'adding_three_numbers', title: 'Adding Three Numbers', lesson: { sections: [{ heading: 'Add Step by Step', content: 'When you add three numbers, start with the first two, then add the third. For 2 + 3 + 1: first 2 + 3 = 5, then 5 + 1 = 6!', visual: '2 + 3 + 1 → Step 1: 2+3=5 → Step 2: 5+1=6 ✅' }, { heading: 'Look for Friends of 10', content: 'Sometimes two numbers add up to 10. In 7 + 4 + 3, see that 7 + 3 = 10. Then 10 + 4 = 14. Much easier!', visual: '7 + 4 + 3 → 7+3=10 → 10+4=14 🎯' }], keyPoints: ['Add three numbers step by step', 'Look for pairs that make 10', 'Order doesn\'t matter in addition'], funFact: 'Fun Fact: Adding numbers in any order gives the same answer. This is called the "commutative property"!' }, quiz: [{ q: 'What is 2 + 3 + 4?', a: ['8', '9', '10', 'None of the above'], correct: 1, type: 'mcq' }, { q: 'You can add numbers in any order.', a: ['True', 'False'], correct: 0, type: 'tf' }, { q: '5 + 5 + 2 = ?', a: ['10', '12', '11', 'None of the above'], correct: 1, type: 'mcq' }, { q: 'Looking for "friends of 10" makes adding easier.', a: ['True', 'False'], correct: 0, type: 'tf' }, { q: '1 + 8 + 2 = ?', a: ['10', '11', '12', 'None of the above'], correct: 1, type: 'mcq' }] },
    { id: 'word_problems_add', title: 'Addition Word Problems', lesson: { sections: [{ heading: 'Stories with Numbers', content: 'Word problems are math stories! "Sam has 3 apples. Mom gives him 4 more. How many now?" The word "more" tells you to add: 3 + 4 = 7!', visual: '🍎🍎🍎 + 🍎🍎🍎🍎 = 🍎🍎🍎🍎🍎🍎🍎 = 7!' }, { heading: 'Key Words', content: 'Words like "more," "total," "together," and "in all" mean you should ADD. Read carefully and find the numbers!', visual: '🔑 More, total, together, in all = ADD!' }], keyPoints: ['"More" and "total" mean add', 'Find the numbers in the story', 'Write the number sentence and solve'], funFact: 'Fun Fact: Ancient Egyptians used math word problems too — they wrote them on papyrus scrolls over 3,000 years ago!' }, quiz: [{ q: 'Ana has 5 toys. She gets 3 more. How many?', a: ['2', '8', '15', 'None of the above'], correct: 1, type: 'mcq' }, { q: 'The word "more" means subtract.', a: ['True', 'False'], correct: 1, type: 'tf' }, { q: 'Tom ate 2 cookies, then 4 more. Total?', a: ['2', '6', '8', 'None of the above'], correct: 1, type: 'mcq' }, { q: '"Together" means you should add.', a: ['True', 'False'], correct: 0, type: 'tf' }, { q: '6 birds and 3 more birds = __ birds in all', a: ['3', '9', '18', 'None of the above'], correct: 1, type: 'mcq' }] },
  ],
  subtraction_intro: [
    { id: 'subtraction_pictures', title: 'Subtraction with Pictures', lesson: { sections: [{ heading: 'Cross Them Out!', content: 'To subtract, draw the first number as pictures, then cross out the second number. Count what\'s left! 5 - 2: draw 5 stars, cross out 2, count 3 left.', visual: '⭐⭐⭐⭐⭐ → cross out 2 → ⭐⭐⭐ = 3!' }, { heading: 'Taking Away', content: 'Subtraction means taking away. If you have 8 crayons and give 3 to a friend, you have 8 - 3 = 5 left.', visual: '🖍️🖍️🖍️🖍️🖍️🖍️🖍️🖍️ give 3 away → 🖍️🖍️🖍️🖍️🖍️ = 5 left' }], keyPoints: ['Draw pictures and cross out to subtract', 'Count what\'s left after crossing out', 'Subtraction means taking away'], funFact: 'Fun Fact: The minus sign (−) was invented in the 1400s by a German mathematician!' }, quiz: [{ q: '7 - 3 = ?', a: ['3', '4', '10', 'None of the above'], correct: 1, type: 'mcq' }, { q: 'Subtraction means adding more.', a: ['True', 'False'], correct: 1, type: 'tf' }, { q: '🍭🍭🍭🍭🍭 take away 2 = ?', a: ['2', '3', '7', 'None of the above'], correct: 1, type: 'mcq' }, { q: 'Drawing pictures helps with subtraction.', a: ['True', 'False'], correct: 0, type: 'tf' }, { q: '9 - 4 = ?', a: ['4', '5', '6', 'None of the above'], correct: 1, type: 'mcq' }] },
    { id: 'subtract_word_problems', title: 'Subtraction Word Problems', lesson: { sections: [{ heading: 'Taking Away Stories', content: '"Lisa had 9 stickers. She gave 4 to Ben. How many left?" The words "gave away" and "left" mean subtract: 9 - 4 = 5!', visual: '🌟 Had 9, gave 4 → 9 - 4 = 5 left' }, { heading: 'Clue Words', content: 'Words like "left," "fewer," "take away," and "how many more" often mean subtract. Look for these clues!', visual: '🔑 Left, fewer, take away, difference = SUBTRACT!' }], keyPoints: ['"Left" and "fewer" mean subtract', 'Find the two numbers in the story', 'Subtract the smaller from the bigger'], funFact: 'Fun Fact: The word "subtract" comes from Latin and means "to pull away from beneath."' }, quiz: [{ q: 'Max had 8 balls. He lost 3. How many left?', a: ['3', '5', '11', 'None of the above'], correct: 1, type: 'mcq' }, { q: '"How many left" means you should add.', a: ['True', 'False'], correct: 1, type: 'tf' }, { q: '10 birds, 6 fly away. How many stay?', a: ['4', '6', '16', 'None of the above'], correct: 0, type: 'mcq' }, { q: '"Fewer" is a clue word for subtraction.', a: ['True', 'False'], correct: 0, type: 'tf' }, { q: 'Sara had 7 books. She returned 2. How many now?', a: ['5', '9', '2', 'None of the above'], correct: 0, type: 'mcq' }] },
    { id: 'fact_families', title: 'Fact Families', lesson: { sections: [{ heading: 'Addition & Subtraction Are Related!', content: 'A fact family uses the same 3 numbers in different ways. With 3, 5, and 8: 3+5=8, 5+3=8, 8-3=5, 8-5=3. They\'re all connected!', visual: '🏠 Fact family for 3, 5, 8: 3+5=8 | 5+3=8 | 8-3=5 | 8-5=3' }, { heading: 'Checking Your Work', content: 'If you solve 9-4=5, you can check by adding: 5+4=9. It works! Addition helps check subtraction.', visual: '✅ 9-4=5 → Check: 5+4=9 ✓' }], keyPoints: ['Fact families have 3 numbers and 4 equations', 'Addition and subtraction are opposites', 'Use addition to check subtraction'], funFact: 'Fun Fact: The idea of "inverse operations" (opposites like + and −) is one of the biggest ideas in all of mathematics!' }, quiz: [{ q: 'If 4+6=10, then 10-4=?', a: ['4', '6', '14', 'None of the above'], correct: 1, type: 'mcq' }, { q: 'Addition and subtraction are related.', a: ['True', 'False'], correct: 0, type: 'tf' }, { q: 'Which belongs in the fact family 2, 7, 9?', a: ['2+7=9', '3+6=9', '2+9=7', 'None of the above'], correct: 0, type: 'mcq' }, { q: 'You can check subtraction with addition.', a: ['True', 'False'], correct: 0, type: 'tf' }, { q: 'What is the fact family for 5+3=8?', a: ['5+3=8, 3+5=8, 8-5=3, 8-3=5', '5-3=2, 3-5=2', '5×3=15', 'None of the above'], correct: 0, type: 'mcq' }] },
  ],
  measurement_basics: [
    { id: 'comparing_sizes', title: 'Comparing Sizes', lesson: { sections: [{ heading: 'Longer and Shorter', content: 'To compare lengths, put things side by side. Which pencil is longer? Which ribbon is shorter? Line them up at the same starting point!', visual: '📏 Long pencil ═══════ | Short pencil ════' }, { heading: 'Taller and Shorter', content: 'Height is how tall something is. A giraffe is taller than a dog. A flower is shorter than a tree. Compare things around you!', visual: '🦒 Tall! | 🐕 Short! | Always compare to something!' }], keyPoints: ['Line things up to compare length', 'Longer means more length', 'Taller means more height'], funFact: 'Fun Fact: The tallest person ever recorded was 8 feet 11 inches — that\'s taller than a basketball hoop!' }, quiz: [{ q: 'To compare lengths, you should...', a: ['Stack things', 'Line up at the same start', 'Guess', 'None of the above'], correct: 1, type: 'mcq' }, { q: 'A giraffe is shorter than a dog.', a: ['True', 'False'], correct: 1, type: 'tf' }, { q: 'Which word means more length?', a: ['Shorter', 'Longer', 'Lighter', 'None of the above'], correct: 1, type: 'mcq' }, { q: 'Height is how tall something is.', a: ['True', 'False'], correct: 0, type: 'tf' }, { q: 'Which is taller: a tree or a flower?', a: ['Flower', 'Tree', 'Same height', 'None of the above'], correct: 1, type: 'mcq' }] },
    { id: 'heavy_light', title: 'Heavy & Light', lesson: { sections: [{ heading: 'Weighing Things', content: 'Weight is how heavy something is. A watermelon is heavy. A feather is light. You can use a balance scale to compare!', visual: '⚖️ Heavy 🍉 vs Light 🪶' }, { heading: 'Heavier and Lighter', content: 'Hold one thing in each hand. Which feels heavier? A book is heavier than a crayon. An elephant is heavier than a cat!', visual: '📚 Heavy! vs 🖍️ Light! → The book is heavier!' }], keyPoints: ['Weight is how heavy something is', 'Use a balance to compare weights', 'Heavier things push the scale down'], funFact: 'Fun Fact: An elephant weighs about the same as 80 first-graders standing together!' }, quiz: [{ q: 'Which is heavier: a feather or a rock?', a: ['Feather', 'Rock', 'Same', 'None of the above'], correct: 1, type: 'mcq' }, { q: 'A balance scale compares weights.', a: ['True', 'False'], correct: 0, type: 'tf' }, { q: 'Which is lighter?', a: ['A car', 'A pencil', 'A table', 'None of the above'], correct: 1, type: 'mcq' }, { q: 'Weight is how long something is.', a: ['True', 'False'], correct: 1, type: 'tf' }, { q: 'What tool measures weight?', a: ['Ruler', 'Scale', 'Clock', 'None of the above'], correct: 1, type: 'mcq' }] },
    { id: 'time_basics', title: 'Telling Time Basics', lesson: { sections: [{ heading: 'The Clock', content: 'A clock has two hands. The short hand shows the hour. The long hand shows the minutes. When the long hand points to 12, it\'s exactly on the hour!', visual: '🕐 Short hand = hour | Long hand = minutes | 12 o\'clock = both point up!' }, { heading: 'O\'Clock Times', content: 'At 3 o\'clock, the short hand points to 3 and the long hand points to 12. At 7 o\'clock, the short hand is on 7 and long hand on 12.', visual: '🕒 3:00 | 🕖 7:00 — Long hand always at 12 for o\'clock times!' }], keyPoints: ['Short hand = hours', 'Long hand = minutes', 'O\'clock means the long hand is on 12'], funFact: 'Fun Fact: The first clocks didn\'t have minute hands — they only showed hours!' }, quiz: [{ q: 'The short hand on a clock shows...', a: ['Minutes', 'Hours', 'Seconds', 'None of the above'], correct: 1, type: 'mcq' }, { q: 'At 5 o\'clock, the long hand points to 12.', a: ['True', 'False'], correct: 0, type: 'tf' }, { q: 'How many hands does a clock have?', a: ['1', '2', '3', 'None of the above'], correct: 1, type: 'mcq' }, { q: 'The long hand shows hours.', a: ['True', 'False'], correct: 1, type: 'tf' }, { q: 'At what o\'clock is the short hand on 6?', a: ['12 o\'clock', '3 o\'clock', '6 o\'clock', 'None of the above'], correct: 2, type: 'mcq' }] },
  ],

  // ══════════ MATH GRADE 2 ══════════
  addition_basics: [
    { id: 'regrouping_add', title: 'Adding with Regrouping', lesson: { sections: [{ heading: 'Carrying Over', content: 'When adding digits that make more than 9, you "regroup" (carry). 17 + 15: add ones first 7+5=12. Write 2, carry 1. Then 1+1+1=3. Answer: 32!', visual: '17 + 15 → ones: 7+5=12 (write 2, carry 1) → tens: 1+1+1=3 → 32!' }, { heading: 'Practice Makes Perfect', content: 'Always start with the ones column (right side). If the sum is 10 or more, carry to the tens. Then add the tens column.', visual: '📝 Step 1: Add ones → Step 2: Carry if needed → Step 3: Add tens' }], keyPoints: ['Start adding from the right (ones)', 'Carry when digits sum to 10+', 'Add the carried number to the next column'], funFact: 'Fun Fact: The word "carry" in math comes from when people used an abacus and physically carried beads to the next row!' }, quiz: [{ q: '18 + 14 = ?', a: ['22', '32', '42', 'None of the above'], correct: 1, type: 'mcq' }, { q: 'You regroup when ones add up to 10 or more.', a: ['True', 'False'], correct: 0, type: 'tf' }, { q: '25 + 17 = ?', a: ['32', '42', '52', 'None of the above'], correct: 1, type: 'mcq' }, { q: 'Always start adding from the left.', a: ['True', 'False'], correct: 1, type: 'tf' }, { q: '36 + 28 = ?', a: ['54', '64', '58', 'None of the above'], correct: 1, type: 'mcq' }] },
    { id: 'mental_math_add', title: 'Mental Math Addition', lesson: { sections: [{ heading: 'Add in Your Head', content: 'Mental math means solving without writing! To add 9 to a number, add 10 then subtract 1. 9+6: think 10+6=16, then 16-1=15!', visual: '🧠 9+6 → think 10+6=16 → 16-1=15! Quick!' }, { heading: 'Make a Ten', content: 'Break numbers to make 10. For 8+5: take 2 from the 5 to make 8+2=10. Then add the leftover 3. 10+3=13!', visual: '8+5 → 8+2+3 → 10+3 = 13 🎯' }], keyPoints: ['Add 9 by adding 10 then subtracting 1', 'Break numbers apart to make 10', 'Practice makes mental math faster'], funFact: 'Fun Fact: Some people can add huge numbers in their head faster than a calculator — they practice mental math every day!' }, quiz: [{ q: '9 + 7 = ? (add 10, subtract 1)', a: ['15', '16', '17', 'None of the above'], correct: 1, type: 'mcq' }, { q: 'Mental math means using a calculator.', a: ['True', 'False'], correct: 1, type: 'tf' }, { q: '8 + 6 = ? (make a 10)', a: ['13', '14', '15', 'None of the above'], correct: 1, type: 'mcq' }, { q: 'Breaking numbers to make 10 helps with mental math.', a: ['True', 'False'], correct: 0, type: 'tf' }, { q: '9 + 5 = ?', a: ['13', '14', '15', 'None of the above'], correct: 1, type: 'mcq' }] },
    { id: 'doubles_near', title: 'Doubles & Near Doubles', lesson: { sections: [{ heading: 'Doubles', content: 'Doubles are numbers added to themselves! 3+3=6, 5+5=10, 7+7=14. Memorize your doubles — they make other math easier!', visual: '🎯 3+3=6 | 5+5=10 | 7+7=14 | 8+8=16' }, { heading: 'Near Doubles', content: 'Near doubles are doubles plus 1. 6+7 is like 6+6+1=13. Or 8+9 is 8+8+1=17. Use doubles you know to solve tricky ones!', visual: '6+7 → 6+6=12 → 12+1=13! Easy!' }], keyPoints: ['Doubles: same number + same number', 'Near doubles: doubles plus 1', 'Knowing doubles helps with other facts'], funFact: 'Fun Fact: Double 1 cent every day for 30 days and you\'d have over $5 million!' }, quiz: [{ q: '6 + 6 = ?', a: ['10', '11', '12', 'None of the above'], correct: 2, type: 'mcq' }, { q: 'A near double is a double plus 1.', a: ['True', 'False'], correct: 0, type: 'tf' }, { q: '7 + 8 = ? (near doubles)', a: ['14', '15', '16', 'None of the above'], correct: 1, type: 'mcq' }, { q: '9 + 9 = ?', a: ['17', '18', '19', 'None of the above'], correct: 1, type: 'mcq' }, { q: '4 + 5 is a near double of 4 + 4.', a: ['True', 'False'], correct: 0, type: 'tf' }] },
  ],
  subtraction_stories: [
    { id: 'subtract_regrouping', title: 'Subtracting with Regrouping', lesson: { sections: [{ heading: 'Borrowing', content: 'When the top digit is smaller, borrow from the tens! 42-17: You can\'t do 2-7, so borrow 1 ten to make 12-7=5. Then 3-1=2. Answer: 25!', visual: '42 - 17 → borrow: 12-7=5, 3-1=2 → Answer: 25' }, { heading: 'Step by Step', content: 'Start at the ones place. If you can\'t subtract, borrow from tens. Cross out the tens digit, add 10 to the ones, then subtract.', visual: '📝 Can\'t subtract? → Borrow 1 ten → Add 10 to ones → Now subtract!' }], keyPoints: ['Borrow when the top digit is smaller', 'Cross out tens, add 10 to ones', 'Always start from the right'], funFact: 'Fun Fact: In some countries, they call borrowing "exchanging" — you exchange 1 ten for 10 ones!' }, quiz: [{ q: '43 - 18 = ?', a: ['25', '35', '15', 'None of the above'], correct: 0, type: 'mcq' }, { q: 'You borrow when the top number is bigger.', a: ['True', 'False'], correct: 1, type: 'tf' }, { q: '52 - 27 = ?', a: ['25', '35', '15', 'None of the above'], correct: 0, type: 'mcq' }, { q: 'Start subtracting from the ones place.', a: ['True', 'False'], correct: 0, type: 'tf' }, { q: '61 - 34 = ?', a: ['27', '37', '17', 'None of the above'], correct: 0, type: 'mcq' }] },
    { id: 'checking_subtraction', title: 'Checking Subtraction', lesson: { sections: [{ heading: 'Use Addition to Check', content: 'After subtracting, check your answer by adding! If 15-8=7, check: 7+8=15 ✓ If it matches the original number, you\'re right!', visual: '✅ 15-8=7 → Check: 7+8=15 ✓ Correct!' }, { heading: 'Estimate First', content: 'Before solving, estimate. Round to the nearest 10. 47-21 is about 50-20=30. The real answer (26) should be close to 30.', visual: '🎯 47-21 ≈ 50-20 = 30 | Actual: 26 ✓ Close!' }], keyPoints: ['Add your answer to check subtraction', 'Estimate first to catch big mistakes', 'Rounding to 10s makes estimating easy'], funFact: 'Fun Fact: NASA engineers always estimate answers before using calculators to make sure the answers make sense!' }, quiz: [{ q: 'To check 20-8=12, you should...', a: ['Subtract again', 'Do 12+8', 'Do 20+8', 'None of the above'], correct: 1, type: 'mcq' }, { q: 'Estimation helps catch mistakes.', a: ['True', 'False'], correct: 0, type: 'tf' }, { q: 'Estimate: 48-19 ≈ ?', a: ['20', '30', '40', 'None of the above'], correct: 1, type: 'mcq' }, { q: '25-13=12. Check: 12+13=?', a: ['23', '25', '26', 'None of the above'], correct: 1, type: 'mcq' }, { q: 'Rounding to 10s helps with estimation.', a: ['True', 'False'], correct: 0, type: 'tf' }] },
    { id: 'comparison_subtraction', title: 'Comparing with Subtraction', lesson: { sections: [{ heading: 'How Many More?', content: '"How many more" means subtract! If Ana has 12 stickers and Ben has 7, how many more does Ana have? 12-7=5 more!', visual: '👧 Ana: 12 stickers | 👦 Ben: 7 stickers → 12-7=5 more' }, { heading: 'Finding the Difference', content: 'The "difference" between two numbers is found by subtracting. The difference between 15 and 9 is 15-9=6.', visual: '📊 Difference = bigger - smaller = 15-9 = 6' }], keyPoints: ['"How many more" means subtract', '"Difference" means subtract', 'Subtract smaller from bigger'], funFact: 'Fun Fact: Comparing is one of the oldest uses of math — ancient traders compared prices to find the best deals!' }, quiz: [{ q: 'Sam has 14 toys, Jo has 9. How many more does Sam have?', a: ['4', '5', '23', 'None of the above'], correct: 1, type: 'mcq' }, { q: '"How many more" means add.', a: ['True', 'False'], correct: 1, type: 'tf' }, { q: 'What is the difference between 18 and 11?', a: ['7', '8', '29', 'None of the above'], correct: 0, type: 'mcq' }, { q: 'Difference means subtracting.', a: ['True', 'False'], correct: 0, type: 'tf' }, { q: 'Kim read 20 pages, Lee read 13. Difference?', a: ['7', '33', '8', 'None of the above'], correct: 0, type: 'mcq' }] },
  ],
  place_value: [
    { id: 'hundreds_place', title: 'Hundreds Place', lesson: { sections: [{ heading: 'Ones, Tens, Hundreds', content: 'In the number 345: the 5 is in the ones place, the 4 is in the tens place, and the 3 is in the hundreds place. 3 hundreds = 300!', visual: '345 → 3 hundreds (300) + 4 tens (40) + 5 ones (5)' }, { heading: 'Expanded Form', content: 'Expanded form breaks a number apart: 527 = 500 + 20 + 7. This shows the value of each digit!', visual: '527 = 500 + 20 + 7 ← Expanded form!' }], keyPoints: ['Hundreds place is the third digit', 'Each place is 10 times bigger', 'Expanded form shows each digit\'s value'], funFact: 'Fun Fact: Our number system is called "base 10" because each place is worth 10 times the place to its right!' }, quiz: [{ q: 'In 482, what is the value of the 4?', a: ['4', '40', '400', 'None of the above'], correct: 2, type: 'mcq' }, { q: 'The hundreds place is the second digit.', a: ['True', 'False'], correct: 1, type: 'tf' }, { q: 'What is 300 + 50 + 6?', a: ['3056', '356', '365', 'None of the above'], correct: 1, type: 'mcq' }, { q: 'Expanded form breaks numbers apart.', a: ['True', 'False'], correct: 0, type: 'tf' }, { q: 'In 729, the 2 is in the ___ place.', a: ['Ones', 'Tens', 'Hundreds', 'None of the above'], correct: 1, type: 'mcq' }] },
    { id: 'comparing_numbers_pv', title: 'Comparing Big Numbers', lesson: { sections: [{ heading: 'Compare Digit by Digit', content: 'To compare 347 and 352, start at the hundreds (both 3). Then tens: 4 vs 5. Since 4<5, we know 347 < 352!', visual: '347 vs 352 → hundreds: 3=3 → tens: 4<5 → 347 < 352' }, { heading: 'Greater, Less, Equal', content: 'Use > (greater than), < (less than), = (equal to). 500 > 499. 201 < 210. 350 = 350.', visual: '> means greater | < means less | = means equal' }], keyPoints: ['Compare from left to right', 'Start with the biggest place value', 'Use >, <, and = signs'], funFact: 'Fun Fact: The equals sign (=) was invented in 1557 by a Welsh mathematician who was tired of writing "is equal to" over and over!' }, quiz: [{ q: 'Which is greater: 456 or 465?', a: ['456', '465', 'They are equal', 'None of the above'], correct: 1, type: 'mcq' }, { q: '399 > 400.', a: ['True', 'False'], correct: 1, type: 'tf' }, { q: 'Compare: 521 ___ 519', a: ['<', '>', '=', 'None of the above'], correct: 1, type: 'mcq' }, { q: 'Start comparing from the ones place.', a: ['True', 'False'], correct: 1, type: 'tf' }, { q: 'Which is smallest: 180, 108, 801?', a: ['180', '108', '801', 'None of the above'], correct: 1, type: 'mcq' }] },
    { id: 'rounding_numbers', title: 'Rounding Numbers', lesson: { sections: [{ heading: 'Round to the Nearest Ten', content: 'Look at the ones digit. If it\'s 5 or more, round up. If it\'s 4 or less, round down. 37 rounds to 40. 32 rounds to 30.', visual: '37 → ones is 7 (5+) → round UP to 40 | 32 → ones is 2 (4−) → round DOWN to 30' }, { heading: 'Why Round?', content: 'Rounding makes numbers easier to work with. "About 50 people" is easier to think about than "exactly 47 people."', visual: '47 people ≈ about 50 people — easier to think about!' }], keyPoints: ['5 or more → round up', '4 or less → round down', 'Rounding makes numbers simpler'], funFact: 'Fun Fact: Weather forecasters round temperatures all the time — that\'s why they say "around 70 degrees" instead of 68.4 degrees!' }, quiz: [{ q: 'Round 43 to the nearest ten.', a: ['40', '50', '43', 'None of the above'], correct: 0, type: 'mcq' }, { q: 'If the ones digit is 5, round up.', a: ['True', 'False'], correct: 0, type: 'tf' }, { q: 'Round 78 to the nearest ten.', a: ['70', '80', '75', 'None of the above'], correct: 1, type: 'mcq' }, { q: 'Rounding makes numbers exact.', a: ['True', 'False'], correct: 1, type: 'tf' }, { q: 'Round 55 to the nearest ten.', a: ['50', '60', '55', 'None of the above'], correct: 1, type: 'mcq' }] },
  ],
  money_basics: [
    { id: 'making_change', title: 'Making Change', lesson: { sections: [{ heading: 'Count Up to Make Change', content: 'If something costs 35 cents and you pay with 50 cents, count up from 35: 35, 40, 45, 50. That\'s 15 cents change!', visual: '🪙 35¢ → 40¢(+5) → 45¢(+5) → 50¢(+5) = 15¢ change!' }, { heading: 'Using Different Coins', content: 'You can make the same amount with different coins! 25¢ = 1 quarter = 2 dimes + 1 nickel = 5 nickels = 25 pennies.', visual: '25¢ = 🪙quarter | 🪙🪙dime+🪙nickel | 🪙🪙🪙🪙🪙 nickels' }], keyPoints: ['Count up from the price to make change', 'Same amount, different coin combinations', 'Start with the biggest coins first'], funFact: 'Fun Fact: The first coins ever made were in ancient Turkey about 2,700 years ago — they were made of a gold-silver mixture!' }, quiz: [{ q: 'Item costs 40¢, pay 50¢. Change?', a: ['5¢', '10¢', '15¢', 'None of the above'], correct: 1, type: 'mcq' }, { q: 'You can make 30¢ with coins in only one way.', a: ['True', 'False'], correct: 1, type: 'tf' }, { q: 'How many nickels make 25¢?', a: ['3', '4', '5', 'None of the above'], correct: 2, type: 'mcq' }, { q: 'Count up to make change.', a: ['True', 'False'], correct: 0, type: 'tf' }, { q: 'Item costs 65¢, pay $1.00. Change?', a: ['25¢', '35¢', '45¢', 'None of the above'], correct: 1, type: 'mcq' }] },
    { id: 'dollar_bills', title: 'Dollars & Cents', lesson: { sections: [{ heading: '100 Cents = 1 Dollar', content: 'One dollar equals 100 cents. We write it as $1.00. The dot separates dollars from cents. $2.50 means 2 dollars and 50 cents.', visual: '💵 $1.00 = 100¢ | $2.50 = 2 dollars + 50 cents' }, { heading: 'Adding Money', content: 'Add money like regular numbers, but keep the decimal point lined up. $1.25 + $2.30 = $3.55. Don\'t forget the dollar sign!', visual: '💰 $1.25 + $2.30 = $3.55' }], keyPoints: ['100 cents = 1 dollar', 'Use $ and decimal point for money', 'Line up decimal points when adding'], funFact: 'Fun Fact: If you stacked one million dollar bills, the pile would be about 360 feet tall — as high as a 30-story building!' }, quiz: [{ q: 'How many cents equal one dollar?', a: ['10', '50', '100', 'None of the above'], correct: 2, type: 'mcq' }, { q: '$3.25 means 3 dollars and 25 cents.', a: ['True', 'False'], correct: 0, type: 'tf' }, { q: '$1.50 + $2.25 = ?', a: ['$3.25', '$3.75', '$4.25', 'None of the above'], correct: 1, type: 'mcq' }, { q: 'The decimal point separates dollars and cents.', a: ['True', 'False'], correct: 0, type: 'tf' }, { q: 'Which is more: $4.99 or $5.00?', a: ['$4.99', '$5.00', 'Same', 'None of the above'], correct: 1, type: 'mcq' }] },
    { id: 'money_word_problems', title: 'Money Word Problems', lesson: { sections: [{ heading: 'Shopping Math', content: 'Maya buys a book for $3.50 and a pencil for $0.75. Total? $3.50 + $0.75 = $4.25. She pays with $5.00. Change: $5.00 - $4.25 = $0.75.', visual: '📚 $3.50 + ✏️ $0.75 = $4.25 total | Pay $5.00 → $0.75 change' }, { heading: 'Do I Have Enough?', content: 'Compare your money to the price. If the toy costs $7.50 and you have $6.00, you need $1.50 more. Subtract to find out!', visual: '🧸 Costs $7.50 | You have $6.00 | Need: $7.50-$6.00 = $1.50 more' }], keyPoints: ['Add prices to find totals', 'Subtract to find change', 'Compare money to prices'], funFact: 'Fun Fact: The first paper money was invented in China over 1,000 years ago — it was much easier to carry than heavy coins!' }, quiz: [{ q: 'Apple $1.25 + Juice $0.75. Total?', a: ['$1.50', '$2.00', '$2.25', 'None of the above'], correct: 1, type: 'mcq' }, { q: 'Subtract to find change.', a: ['True', 'False'], correct: 0, type: 'tf' }, { q: 'Have $10, spend $6.50. Change?', a: ['$3.00', '$3.50', '$4.50', 'None of the above'], correct: 1, type: 'mcq' }, { q: 'If something costs $5 and you have $3, you can buy it.', a: ['True', 'False'], correct: 1, type: 'tf' }, { q: 'Pen $2.00 + Eraser $0.50 + Ruler $1.50 = ?', a: ['$3.50', '$4.00', '$4.50', 'None of the above'], correct: 1, type: 'mcq' }] },
  ],
  time_telling: [
    { id: 'half_quarter', title: 'Half Past & Quarter', lesson: { sections: [{ heading: 'Half Past', content: 'Half past means the minute hand is at 6 (the bottom). Half past 3 means 3:30. The hour hand is between 3 and 4.', visual: '🕞 Half past 3 = 3:30 — minute hand at 6!' }, { heading: 'Quarter Past & Quarter To', content: 'Quarter past means :15 (minute hand at 3). Quarter to means :45 (minute hand at 9). Quarter past 2 = 2:15. Quarter to 5 = 4:45.', visual: '🕑 Quarter past 2 = 2:15 | Quarter to 5 = 4:45' }], keyPoints: ['Half past = :30 (minute hand at 6)', 'Quarter past = :15 (minute hand at 3)', 'Quarter to = :45 (minute hand at 9)'], funFact: 'Fun Fact: "Half past" and "quarter past" come from fractions — half of 60 minutes is 30, and a quarter is 15!' }, quiz: [{ q: 'Half past 7 = ?', a: ['7:15', '7:30', '7:45', 'None of the above'], correct: 1, type: 'mcq' }, { q: 'Quarter past means :45.', a: ['True', 'False'], correct: 1, type: 'tf' }, { q: 'Quarter to 3 = ?', a: ['2:45', '3:15', '3:45', 'None of the above'], correct: 0, type: 'mcq' }, { q: 'At half past, the minute hand points to 6.', a: ['True', 'False'], correct: 0, type: 'tf' }, { q: 'Quarter past 10 = ?', a: ['10:15', '10:30', '10:45', 'None of the above'], correct: 0, type: 'mcq' }] },
    { id: 'am_pm', title: 'AM & PM', lesson: { sections: [{ heading: 'Two Halves of the Day', content: 'AM is from midnight to noon (morning). PM is from noon to midnight (afternoon/night). 8:00 AM is morning. 8:00 PM is night.', visual: '☀️ AM = morning (midnight → noon) | 🌙 PM = afternoon/night (noon → midnight)' }, { heading: 'Using AM and PM', content: 'School starts at 8:30 AM (morning). Dinner is at 6:00 PM (evening). Bedtime is 8:00 PM (night). Always use AM or PM so people know which time!', visual: '🏫 8:30 AM school | 🍽️ 6:00 PM dinner | 😴 8:00 PM bedtime' }], keyPoints: ['AM = before noon (morning)', 'PM = after noon (afternoon/night)', 'Noon is 12:00 PM, midnight is 12:00 AM'], funFact: 'Fun Fact: AM stands for "ante meridiem" (before midday) and PM stands for "post meridiem" (after midday) in Latin!' }, quiz: [{ q: 'School starts at 8:00 ___.', a: ['AM', 'PM', 'Either', 'None of the above'], correct: 0, type: 'mcq' }, { q: 'PM means morning.', a: ['True', 'False'], correct: 1, type: 'tf' }, { q: 'Noon is 12:00 ___.', a: ['AM', 'PM', 'Neither', 'None of the above'], correct: 1, type: 'mcq' }, { q: 'AM stands for "ante meridiem."', a: ['True', 'False'], correct: 0, type: 'tf' }, { q: 'Bedtime at 9:00 is ___.', a: ['AM', 'PM', 'Noon', 'None of the above'], correct: 1, type: 'mcq' }] },
    { id: 'elapsed_time', title: 'How Much Time Passed?', lesson: { sections: [{ heading: 'Counting Time', content: 'Elapsed time is how much time passed. If a movie starts at 2:00 and ends at 4:00, the movie was 2 hours long!', visual: '🎬 Start: 2:00 → End: 4:00 → 4-2 = 2 hours!' }, { heading: 'Count Forward', content: 'From 3:30 to 5:00: count 30 minutes to get to 4:00, then 1 more hour to 5:00. Total: 1 hour 30 minutes!', visual: '3:30 → 4:00 (30 min) → 5:00 (1 hr) = 1 hr 30 min' }], keyPoints: ['Elapsed time = end time − start time', 'Count forward from start to end', '60 minutes = 1 hour'], funFact: 'Fun Fact: The longest movie ever made is over 35 days long — that\'s 857 hours!' }, quiz: [{ q: '1:00 to 3:00 = how many hours?', a: ['1', '2', '3', 'None of the above'], correct: 1, type: 'mcq' }, { q: 'Elapsed time means the start time.', a: ['True', 'False'], correct: 1, type: 'tf' }, { q: '2:30 to 4:30 = ?', a: ['1 hour', '2 hours', '3 hours', 'None of the above'], correct: 1, type: 'mcq' }, { q: '60 minutes equals 1 hour.', a: ['True', 'False'], correct: 0, type: 'tf' }, { q: '10:00 AM to 12:00 PM = ?', a: ['1 hour', '2 hours', '3 hours', 'None of the above'], correct: 1, type: 'mcq' }] },
  ],
  word_problems: [
    { id: 'two_step_problems', title: 'Two-Step Word Problems', lesson: { sections: [{ heading: 'Two Steps!', content: 'Some problems need two steps. "Maya has 12 stickers, gets 5 more, then gives 3 away." Step 1: 12+5=17. Step 2: 17-3=14.', visual: '📝 Step 1: 12+5=17 → Step 2: 17-3=14 stickers' }, { heading: 'Read Carefully', content: 'Read the whole problem first. Find ALL the numbers and operations. Then solve step by step.', visual: '👀 Read → Find numbers → Step 1 → Step 2 → Answer!' }], keyPoints: ['Some problems need two operations', 'Solve one step at a time', 'Read the whole problem before starting'], funFact: 'Fun Fact: Real life is full of multi-step math! Buying groceries involves adding prices and then subtracting from your money.' }, quiz: [{ q: 'Tom has 8 cars, gets 4 more, gives 2 away. How many?', a: ['10', '12', '14', 'None of the above'], correct: 0, type: 'mcq' }, { q: 'Two-step problems only use addition.', a: ['True', 'False'], correct: 1, type: 'tf' }, { q: '15 + 5 - 7 = ?', a: ['12', '13', '17', 'None of the above'], correct: 1, type: 'mcq' }, { q: 'Read the whole problem before solving.', a: ['True', 'False'], correct: 0, type: 'tf' }, { q: 'Sara has $10, earns $5, spends $8. How much left?', a: ['$3', '$7', '$12', 'None of the above'], correct: 1, type: 'mcq' }] },
    { id: 'choosing_operation', title: 'Add or Subtract?', lesson: { sections: [{ heading: 'Clue Words Chart', content: 'ADD: total, sum, together, more, in all, combined. SUBTRACT: left, fewer, difference, remain, take away, how many more.', visual: '➕ total, sum, together, more | ➖ left, fewer, difference, remain' }, { heading: 'Ask: Getting More or Less?', content: 'If the problem is about getting MORE, combining, or joining → ADD. If it\'s about losing, leaving, or comparing → SUBTRACT.', visual: '📈 Getting more? ADD! | 📉 Getting less? SUBTRACT!' }], keyPoints: ['Look for clue words', 'Joining or combining = add', 'Removing or comparing = subtract'], funFact: 'Fun Fact: Computers process billions of additions and subtractions every second — but they use the same clue-word logic you\'re learning!' }, quiz: [{ q: '"How many in all?" means...', a: ['Subtract', 'Add', 'Multiply', 'None of the above'], correct: 1, type: 'mcq' }, { q: '"How many are left?" means add.', a: ['True', 'False'], correct: 1, type: 'tf' }, { q: '8 apples, ate 3. This is:', a: ['Addition', 'Subtraction', 'Neither', 'None of the above'], correct: 1, type: 'mcq' }, { q: '"Together" is a clue for addition.', a: ['True', 'False'], correct: 0, type: 'tf' }, { q: '12 crayons plus 6 more. This is:', a: ['Addition', 'Subtraction', 'Neither', 'None of the above'], correct: 0, type: 'mcq' }] },
    { id: 'number_sentences', title: 'Writing Number Sentences', lesson: { sections: [{ heading: 'Translate Words to Math', content: '"Sam has 9 marbles and finds 4 more" becomes 9 + 4 = 13. Turn the story into a number sentence!', visual: '📖 "9 marbles + 4 more" → ✏️ 9 + 4 = 13' }, { heading: 'Unknown Numbers', content: 'Sometimes the answer is in the middle! "Ana had some cards. She got 5 more and now has 12." Write: ? + 5 = 12, so ? = 7!', visual: '❓ + 5 = 12 → Think: 12 - 5 = 7 → She had 7!' }], keyPoints: ['Turn word problems into number sentences', 'Use + and − signs to write the equation', 'Solve for unknown numbers by working backwards'], funFact: 'Fun Fact: The + sign for addition was first used in a math book in 1489 — that\'s over 500 years ago!' }, quiz: [{ q: '"7 books plus 3 books" as a number sentence:', a: ['7 - 3 = 4', '7 + 3 = 10', '7 × 3 = 21', 'None of the above'], correct: 1, type: 'mcq' }, { q: 'Number sentences use + and − signs.', a: ['True', 'False'], correct: 0, type: 'tf' }, { q: '? + 6 = 14. What is ?', a: ['6', '8', '20', 'None of the above'], correct: 1, type: 'mcq' }, { q: 'Word problems can be written as equations.', a: ['True', 'False'], correct: 0, type: 'tf' }, { q: '"15 take away 9" as a number sentence:', a: ['15 + 9 = 24', '15 − 9 = 6', '9 − 15 = 6', 'None of the above'], correct: 1, type: 'mcq' }] },
  ],
};

// ═══════════════════════════════════════════════════════════════════════════
// Apply the extra links to each loop
// ═══════════════════════════════════════════════════════════════════════════

let added = 0;
let already5 = 0;
let missing = [];

for (const subject of ['math', 'science']) {
  for (const loop of data[subject]) {
    const needed = 5 - loop.links.length;
    if (needed <= 0) {
      already5++;
      continue;
    }
    const extras = EXTRA_LINKS[loop.loop];
    if (!extras) {
      missing.push(`${subject} g${loop.grade} ${loop.loop} (has ${loop.links.length}, needs ${needed} more)`);
      continue;
    }
    const toAdd = extras.slice(0, needed);
    loop.links.push(...toAdd);
    added += toAdd.length;
  }
}

console.log(`Added ${added} links`);
console.log(`Already at 5+: ${already5} loops`);
if (missing.length) {
  console.log(`\nStill need content for ${missing.length} loops:`);
  missing.forEach(m => console.log(`  - ${m}`));
}

// Verify
let allGood = true;
for (const subject of ['math', 'science']) {
  for (const loop of data[subject]) {
    if (loop.links.length !== 5) {
      console.log(`WARNING: ${subject} g${loop.grade} ${loop.loop} has ${loop.links.length} links`);
      allGood = false;
    }
  }
}
if (allGood) {
  console.log('\n✅ All loops have exactly 5 links!');
}

// Write if we added anything
if (added > 0) {
  fs.writeFileSync(FILE, JSON.stringify(data, null, 2));
  console.log(`\nWrote updated lessons.json`);
}
